export type TalentDef = {
  id: string
  name: string
  tree: 'arms' | 'fury' | 'protection'
  tier: number // 1–7
  maxRanks: number
  requires?: string
  pointsRequiredInTree?: number
  description: string
}

/** Classic 1.12 warrior talent layout (mechanical stubs wired where systems exist). */
export const TALENTS: TalentDef[] = [
  // Arms
  { id: 'improved_heroic_strike', name: 'Improved Heroic Strike', tree: 'arms', tier: 1, maxRanks: 3, description: 'Reduces the rage cost of Heroic Strike by 1/2/3.' },
  { id: 'deflection', name: 'Deflection', tree: 'arms', tier: 1, maxRanks: 5, description: 'Increases your Parry chance by 1% per rank.' },
  { id: 'improved_rend', name: 'Improved Rend', tree: 'arms', tier: 1, maxRanks: 3, description: 'Increases the damage of your Rend by 15/25/35%.' },
  { id: 'improved_charge', name: 'Improved Charge', tree: 'arms', tier: 2, maxRanks: 2, pointsRequiredInTree: 5, description: 'Increases rage generated by Charge by 3/6.' },
  { id: 'tactical_mastery', name: 'Tactical Mastery', tree: 'arms', tier: 2, maxRanks: 5, pointsRequiredInTree: 5, description: 'Retain 5 rage per rank when changing stances.' },
  { id: 'improved_thunder_clap', name: 'Improved Thunder Clap', tree: 'arms', tier: 2, maxRanks: 3, pointsRequiredInTree: 5, description: 'Reduces the rage cost of Thunder Clap.' },
  { id: 'anger_management', name: 'Anger Management', tree: 'arms', tier: 3, maxRanks: 1, requires: 'tactical_mastery', pointsRequiredInTree: 10, description: 'Generate 1 rage every 3 seconds while in combat.' },
  { id: 'deep_wounds', name: 'Deep Wounds', tree: 'arms', tier: 3, maxRanks: 3, requires: 'improved_rend', pointsRequiredInTree: 10, description: 'Your critical strikes cause the opponent to bleed.' },
  { id: 'impale', name: 'Impale', tree: 'arms', tier: 4, maxRanks: 2, requires: 'deep_wounds', pointsRequiredInTree: 15, description: 'Increases critical strike damage bonus.' },
  { id: 'two_handed_weapon_spec', name: 'Two-Handed Weapon Specialization', tree: 'arms', tier: 4, maxRanks: 5, pointsRequiredInTree: 15, description: 'Increases damage with two-handed melee weapons.' },
  { id: 'sweeping_strikes', name: 'Sweeping Strikes', tree: 'arms', tier: 5, maxRanks: 1, pointsRequiredInTree: 20, description: 'Your next 5 melee attacks strike an additional nearby opponent.' },
  { id: 'mortal_strike', name: 'Mortal Strike', tree: 'arms', tier: 7, maxRanks: 1, requires: 'sweeping_strikes', pointsRequiredInTree: 30, description: 'A vicious strike that deals weapon damage plus bonus and reduces healing.' },

  // Fury
  { id: 'booming_voice', name: 'Booming Voice', tree: 'fury', tier: 1, maxRanks: 5, description: 'Increases area and duration of shouts.' },
  { id: 'cruelty', name: 'Cruelty', tree: 'fury', tier: 1, maxRanks: 5, description: 'Increases your chance to get a critical strike by 1% per rank.' },
  { id: 'unbridled_wrath', name: 'Unbridled Wrath', tree: 'fury', tier: 2, maxRanks: 5, pointsRequiredInTree: 5, description: 'Gives chance to generate extra rage on white hits.' },
  { id: 'improved_cleave', name: 'Improved Cleave', tree: 'fury', tier: 3, maxRanks: 3, pointsRequiredInTree: 10, description: 'Increases bonus damage of Cleave.' },
  { id: 'piercing_howl', name: 'Piercing Howl', tree: 'fury', tier: 3, maxRanks: 1, pointsRequiredInTree: 10, description: 'Dazes enemies within 10 yards for 6 sec.' },
  { id: 'death_wish', name: 'Death Wish', tree: 'fury', tier: 5, maxRanks: 1, pointsRequiredInTree: 20, description: 'Increases physical damage and makes you immune to fear effects.' },
  { id: 'flurry', name: 'Flurry', tree: 'fury', tier: 6, maxRanks: 5, pointsRequiredInTree: 25, description: 'Increases attack speed after a critical strike.' },
  { id: 'bloodthirst', name: 'Bloodthirst', tree: 'fury', tier: 7, maxRanks: 1, pointsRequiredInTree: 30, description: 'Instantly attack for 45% of your AP.' },

  // Protection
  { id: 'shield_specialization', name: 'Shield Specialization', tree: 'protection', tier: 1, maxRanks: 5, description: 'Increases block chance and rage on block.' },
  { id: 'anticipation', name: 'Anticipation', tree: 'protection', tier: 1, maxRanks: 5, description: 'Increases defense skill.' },
  { id: 'toughness', name: 'Toughness', tree: 'protection', tier: 2, maxRanks: 5, pointsRequiredInTree: 5, description: 'Increases armor from items.' },
  { id: 'iron_will', name: 'Iron Will', tree: 'protection', tier: 2, maxRanks: 5, pointsRequiredInTree: 5, description: 'Increases stun/charm resistance.' },
  { id: 'last_stand', name: 'Last Stand', tree: 'protection', tier: 3, maxRanks: 1, pointsRequiredInTree: 10, description: 'Temporarily grants 30% of max health.' },
  { id: 'defiance', name: 'Defiance', tree: 'protection', tier: 3, maxRanks: 5, pointsRequiredInTree: 10, description: 'Increases threat / damage dealt in Defensive Stance.' },
  { id: 'concussion_blow', name: 'Concussion Blow', tree: 'protection', tier: 5, maxRanks: 1, pointsRequiredInTree: 20, description: 'Stuns the opponent for 5 sec.' },
  { id: 'shield_slam', name: 'Shield Slam', tree: 'protection', tier: 7, maxRanks: 1, requires: 'concussion_blow', pointsRequiredInTree: 30, description: 'Slam the target with your shield for heavy damage.' },
]

export type TalentState = Record<string, number>

export function treePoints(spent: TalentState, tree: TalentDef['tree']): number {
  return TALENTS.filter((t) => t.tree === tree).reduce((s, t) => s + (spent[t.id] ?? 0), 0)
}

export function canSpendPoint(
  spent: TalentState,
  talentId: string,
  availablePoints: number,
): boolean {
  if (availablePoints <= 0) return false
  const t = TALENTS.find((x) => x.id === talentId)
  if (!t) return false
  const cur = spent[talentId] ?? 0
  if (cur >= t.maxRanks) return false
  const treePts = treePoints(spent, t.tree)
  const need = (t.tier - 1) * 5
  if (treePts < need) return false
  if (t.pointsRequiredInTree != null && treePts < t.pointsRequiredInTree && cur === 0) {
    // tier gate already covers most; keep explicit req too
  }
  if (t.requires && (spent[t.requires] ?? 0) < 1) return false
  return true
}

export function talentPointsAvailable(level: number, spent: TalentState): number {
  const earned = Math.max(0, level - 9) // 1 pt/level from 10
  const used = Object.values(spent).reduce((a, b) => a + b, 0)
  return Math.max(0, Math.min(51, earned) - used)
}
