export type QuestDef = {
  id: string
  title: string
  level: number
  zone: 'valley' | 'flats' | 'canyons' | 'ashen'
  giver: string
  turnIn: string
  objectives: { id: string; text: string; count: number; kind: 'kill' | 'collect' | 'talk' }[]
  xpReward: number
  copperReward: number
  itemReward?: string
  breadcrumb?: string
  flavor: string
}

/** 14 original Classic-shaped quests — all text written fresh. */
export const QUESTS: QuestDef[] = [
  {
    id: 'boar_tusk_harvest',
    title: 'Boar Tusk Harvest',
    level: 1,
    zone: 'valley',
    giver: 'Scout Graksha',
    turnIn: 'Scout Graksha',
    objectives: [{ id: 'kill_bristleboar', text: 'Bristleboars Slain', count: 8, kind: 'kill' }],
    xpReward: (1 * 5 + 45) * 4,
    copperReward: 50,
    flavor: 'The valley pigs grow bold. Cut them down and bring proof in blood and tusk.',
  },
  {
    id: 'venom_on_the_flats',
    title: 'Venom On The Flats',
    level: 3,
    zone: 'valley',
    giver: 'Scout Graksha',
    turnIn: 'Scout Graksha',
    objectives: [
      { id: 'kill_scorpid', text: 'Venomtail Scorpids Slain', count: 6, kind: 'kill' },
      { id: 'collect_tail', text: 'Scorpid Tails', count: 4, kind: 'collect' },
    ],
    xpReward: (3 * 5 + 45) * 4,
    copperReward: 120,
    flavor: 'Their stingers drip green as the Emberfang banners. Bring me tails — carefully.',
  },
  {
    id: 'embers_in_the_cave',
    title: 'Embers In The Cave',
    level: 5,
    zone: 'valley',
    giver: 'Warlord Kargha',
    turnIn: 'Warlord Kargha',
    objectives: [{ id: 'kill_emberfang', text: 'Emberfang Cultists Slain', count: 10, kind: 'kill' }],
    xpReward: (5 * 5 + 45) * 4,
    copperReward: 250,
    flavor: 'Cultists whisper in the eastern cave. Silence their chants before the flame spreads.',
  },
  {
    id: 'named_ashmaw',
    title: 'The Cave Tyrant',
    level: 5,
    zone: 'valley',
    giver: 'Warlord Kargha',
    turnIn: 'Warlord Kargha',
    objectives: [{ id: 'kill_ashmaw', text: 'Ashmaw The Cave Tyrant Slain', count: 1, kind: 'kill' }],
    xpReward: (5 * 5 + 45) * 4,
    copperReward: 400,
    flavor: 'A brute leads them. Bring me his end, and the valley will breathe again.',
  },
  {
    id: 'report_to_watchtower',
    title: 'Report To The Watchtower',
    level: 6,
    zone: 'valley',
    giver: 'Scout Graksha',
    turnIn: 'Sergeant Vokna',
    objectives: [{ id: 'talk_vokna', text: 'Speak With Sergeant Vokna', count: 1, kind: 'talk' }],
    xpReward: (6 * 5 + 45) * 4,
    copperReward: 100,
    breadcrumb: 'sunscorch_wolves',
    flavor: 'The canyon gate opens. Carry word to the Sunscorch watchtower — and do not linger.',
  },
  {
    id: 'a_warriors_shield',
    title: "A Warrior's Shield",
    level: 10,
    zone: 'valley',
    giver: 'Warlord Kargha',
    turnIn: 'Warlord Kargha',
    objectives: [{ id: 'kill_shieldbearer', text: 'Unbreakable Shield Recovered', count: 1, kind: 'collect' }],
    xpReward: (10 * 5 + 45) * 4,
    copperReward: 800,
    itemReward: 'unbreakable_bulwark',
    flavor: 'Defensive Stance is earned, not given. Slay the cave shieldbearer and claim what cannot break.',
  },
  {
    id: 'sunscorch_wolves',
    title: 'Sunscorch Wolves',
    level: 8,
    zone: 'flats',
    giver: 'Sergeant Vokna',
    turnIn: 'Sergeant Vokna',
    objectives: [{ id: 'kill_wolf', text: 'Duskmane Wolves Slain', count: 12, kind: 'kill' }],
    xpReward: (8 * 5 + 45) * 4,
    copperReward: 350,
    flavor: 'Packs hunt the road. Thin them before a courier vanishes again.',
  },
  {
    id: 'raider_camps',
    title: 'Raider Camps',
    level: 12,
    zone: 'flats',
    giver: 'Sergeant Vokna',
    turnIn: 'Sergeant Vokna',
    objectives: [{ id: 'kill_raider', text: 'Flatland Raiders Slain', count: 10, kind: 'kill' }],
    xpReward: (12 * 5 + 45) * 4,
    copperReward: 600,
    flavor: 'Humanoids with stolen steel. Drive them from the flats.',
  },
  {
    id: 'oasis_bully',
    title: 'Oasis Bully',
    level: 14,
    zone: 'flats',
    giver: 'Sergeant Vokna',
    turnIn: 'Sergeant Vokna',
    objectives: [{ id: 'kill_named_raider', text: 'Gorruk The Thirsty Slain', count: 1, kind: 'kill' }],
    xpReward: (14 * 5 + 45) * 4,
    copperReward: 900,
    flavor: 'He drinks the oasis dry and laughs. End the joke.',
  },
  {
    id: 'road_to_redrock',
    title: 'Road To Redrock',
    level: 18,
    zone: 'flats',
    giver: 'Sergeant Vokna',
    turnIn: 'Pathfinder Zuln',
    objectives: [{ id: 'talk_zuln', text: 'Speak With Pathfinder Zuln', count: 1, kind: 'talk' }],
    xpReward: (18 * 5 + 45) * 4,
    copperReward: 200,
    flavor: 'The mesas wait. Zuln maps the canyons — find him alive.',
  },
  {
    id: 'sky_shrike_nests',
    title: 'Sky Shrike Nests',
    level: 24,
    zone: 'canyons',
    giver: 'Pathfinder Zuln',
    turnIn: 'Pathfinder Zuln',
    objectives: [{ id: 'kill_shrike', text: 'Sky Shrikes Slain', count: 15, kind: 'kill' }],
    xpReward: (24 * 5 + 45) * 4,
    copperReward: 1200,
    flavor: 'They dive like spears. Clear the ridges so the maps can finish.',
  },
  {
    id: 'cinder_hearts',
    title: 'Cinder Hearts',
    level: 28,
    zone: 'canyons',
    giver: 'Pathfinder Zuln',
    turnIn: 'Pathfinder Zuln',
    objectives: [{ id: 'collect_cinder', text: 'Cinder Hearts', count: 8, kind: 'collect' }],
    xpReward: (28 * 5 + 45) * 4,
    copperReward: 1500,
    flavor: 'Elementals do not bleed — but their cores remember heat. Bring eight.',
  },
  {
    id: 'test_of_fury',
    title: 'The Test Of Fury',
    level: 30,
    zone: 'canyons',
    giver: 'Warlord Kargha',
    turnIn: 'Warlord Kargha',
    objectives: [{ id: 'survive_arena', text: 'Arena Waves Survived', count: 3, kind: 'kill' }],
    xpReward: (30 * 5 + 45) * 4,
    copperReward: 2000,
    flavor: 'Berserker Stance is forged in the arena. Survive three waves. Do not ask for mercy.',
  },
  {
    id: 'ashbound_finale',
    title: "Ashbound's End",
    level: 60,
    zone: 'ashen',
    giver: 'Warlord Kargha',
    turnIn: 'Warlord Kargha',
    objectives: [{ id: 'kill_gormash', text: "Gor'mash The Ashbound Slain", count: 1, kind: 'kill' }],
    xpReward: (60 * 5 + 45) * 8,
    copperReward: 50000,
    flavor: 'The citadel burns night and day. Cut down Gor\'mash and let the ash settle.',
  },
]
